# Generated by Django 5.1 on 2024-08-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('ano', models.CharField(max_length=4)),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
    ]
