# Generated by Django 5.1 on 2024-08-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absolute_cinema', '0002_filmes_diretor_alter_filmes_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='genero',
        ),
    ]
