# Generated by Django 5.1 on 2024-08-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absolute_cinema', '0003_remove_filmes_ano_remove_filmes_diretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='ano',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmes',
            name='diretor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmes',
            name='genero',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
